### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ArtichOwO**
Added `clone` commands and `cpp` for code colors

(The `.gitignore` file is also updated for mac users)

### CODE REVIEW

**Review by CacahueteSansSel — APPROVED** [review]
Super nice ! Let's merge that :D
(I will just fix #5 before that, as it is a pretty big security issue)

**Comment by ArtichOwO** [comment]
Thanks ^^
Np, I'll wait x)

**Comment by CacahueteSansSel** [comment]
Done :) !

**Comment by ArtichOwO** [comment]
Thanks ^^

**Pull request merged**
